import {
  useEffect,
  useState,
} from "react";

import type {
  ChangeEvent,
  CSSProperties,
  Dispatch,
  SetStateAction,
} from "react";

import Modal from "react-bootstrap/Modal";
import Form from "react-bootstrap/Form";
import {
  Col,
  Row,
} from "react-bootstrap";

import { useFormik } from "formik";
import axios from "axios";
import { toast } from "react-toastify";

import { url } from "../../utils/constant";

import {
  batchInitialValues,
  formSchema,
} from "./BatchSchema";

import type {
  BatchFormValues,
} from "./BatchSchema";

import { calcEndDate } from "../calcEndDate";

import {
  GroupAdd,
  School,
  CalendarMonth,
  AccessTime,
  People,
  AttachMoney,
  Tag,
  Event,
  Wifi,
} from "@mui/icons-material";

import ModalHeaderBlock from "../../Common/ModalHeaderBlock";
import ModalFooterBlock from "../../Common/ModalFooterBlock";

// TypeScript:
// Reuse our shared API/domain types.
import type { Batch } from "../../../types/batch";
import type { Course } from "../../../types/course";


// ========================================
// COMPONENT PROPS
// ========================================

interface ModalAddBatchProps {
  show: boolean;

  setShow: Dispatch<
    SetStateAction<boolean>
  >;

  /*
   * After creating a batch we refetch all batches
   * and update the parent state.
   */
  setBatchData: Dispatch<
    SetStateAction<Batch[]>
  >;
}


// ========================================
// API RESPONSE TYPES
// ========================================

interface CourseListResponse {
  courseData: Course[];
}

interface BatchListResponse {
  batchData: Batch[];
}

interface NextBatchNumberResponse {
  newBatch: string;
}


// ========================================
// ADD BATCH PAYLOAD
// ========================================

/*
 * TypeScript:
 * The form values are not exactly the same as the object
 * sent to the backend.
 *
 * The backend expects "fees", while the form temporarily
 * stores the selected course fee as "courseFee".
 *
 * endDate is also calculated by the frontend.
 */
interface AddBatchPayload
  extends BatchFormValues {
  fees: number | "";
  endDate: string;
}


// ========================================
// MODAL STYLE
// ========================================

/*
 * React's normal CSSProperties type does not know about
 * Bootstrap's custom CSS variable.
 *
 * Extending the type lets us keep:
 *
 * --bs-modal-border-radius
 *
 * without using `any`.
 */
const modalStyle:
  CSSProperties & {
    "--bs-modal-border-radius": string;
  } = {
  "--bs-modal-border-radius": "16px",
};


function ModalAddBatch({
  show,
  setShow,
  setBatchData,
}: ModalAddBatchProps) {
  // ========================================
  // STATE
  // ========================================

  /*
   * TypeScript:
   * courseData contains Course objects returned
   * from the backend.
   */
  const [courseData, setCourseData] =
    useState<Course[]>([]);

  const [nextBatchNo, setNextBatchNo] =
    useState<string>("");

  /*
   * Auto-calculated from startDate + course.noOfDays.
   * This is display-only.
   */
  const [endDate, setEndDate] =
    useState<string>("");


  // ========================================
  // AUTH
  // ========================================

  const token =
    localStorage.getItem("token");

  const config = {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  };


  // ========================================
  // MODAL CLOSE
  // ========================================

  const handleClose = (): void => {
    setShow(false);
  };


  // ========================================
  // FORMIK
  // ========================================

  /*
   * TypeScript:
   * <BatchFormValues> tells Formik exactly which
   * properties exist in formik.values.
   *
   * This means TypeScript now knows about:
   *
   * formik.values.startDate
   * formik.values.courseName
   * formik.values.courseFee
   */
  const formik =
    useFormik<BatchFormValues>({
      initialValues:
        batchInitialValues,

      validationSchema:
        formSchema,

      onSubmit: (values) => {
        const newBatch: AddBatchPayload =
          {
            ...values,

            // Use the number generated by the backend.
            batchNumber:
              nextBatchNo,

            /*
             * Backend Batch schema uses "fees",
             * while the form displays "courseFee".
             */
            fees:
              values.courseFee,

            // Automatically calculated date.
            endDate,
          };

        void addBatch(
          newBatch
        );
      },
    });


  // ========================================
  // FETCH COURSES
  // ========================================

  const getCourseData =
    async (): Promise<void> => {
      try {
        /*
         * TypeScript:
         * Axios now knows that res.data.courseData
         * must be Course[].
         */
        const res =
          await axios.get<CourseListResponse>(
            `${url}/allcourse`,
            config
          );

        setCourseData(
          res.data.courseData
        );
      } catch (error: unknown) {
        console.error(
          "Error fetching courses:",
          error
        );
      }
    };


  // ========================================
  // FETCH NEXT BATCH NUMBER
  // ========================================

  const fetchNextBatchNo =
    async (): Promise<void> => {
      try {
        const res =
          await axios.get<NextBatchNumberResponse>(
            `${url}/nextbatchno`,
            config
          );

        const newBatchNumber =
          res.data.newBatch;

        setNextBatchNo(
          newBatchNumber
        );

        /*
         * Keep Formik's batchNumber field synchronized
         * with the number generated by the backend.
         */
        await formik.setFieldValue(
          "batchNumber",
          newBatchNumber
        );
      } catch (error: unknown) {
        console.error(
          "Error fetching next batch no:",
          error
        );

        toast.error(
          "Failed to get next batch number"
        );
      }
    };


  // Fetch course options when the modal component loads.
  useEffect(() => {
    void getCourseData();

    // The original component only fetches courses once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);


  /*
   * Fetch a new batch number whenever the Add Batch
   * modal is opened.
   */
  useEffect(() => {
    if (show) {
      void fetchNextBatchNo();
    }

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [show]);


  // ========================================
  // CALCULATE END DATE
  // ========================================

  useEffect(() => {
    /*
     * TypeScript:
     * Array.find() returns:
     *
     * Course | undefined
     *
     * so optional chaining is required when reading
     * selectedCourse.noOfDays.
     */
    const selectedCourse =
      courseData.find(
        (course) =>
          course.courseName ===
          formik.values.courseName
      );

    const calculated =
      calcEndDate(
        formik.values.startDate,
        selectedCourse?.noOfDays
      );

    setEndDate(calculated);
  }, [
    formik.values.startDate,
    formik.values.courseName,
    courseData,
  ]);


  // ========================================
  // COURSE SELECT CHANGE
  // ========================================

  /*
   * TypeScript:
   * React Bootstrap Form.Select produces a change
   * event from an HTMLSelectElement.
   */
  const handleCourseNameChange = (
    event: ChangeEvent<HTMLSelectElement>
  ): void => {
    const selectedCourse =
      courseData.find(
        (course) =>
          course.courseName ===
          event.target.value
      );

    if (!selectedCourse) {
      return;
    }

    /*
     * Store the selected course information inside
     * Formik's form state.
     */
    void formik.setFieldValue(
      "courseName",
      selectedCourse.courseName
    );

    void formik.setFieldValue(
      "courseFee",
      selectedCourse.courseFee
    );
  };


  // ========================================
  // ADD BATCH
  // ========================================

  const addBatch = async (
    newBatch: AddBatchPayload
  ): Promise<void> => {
    try {
      await axios.post(
        `${url}/addbatch`,
        newBatch,
        config
      );

      /*
       * Refetch the Batch list after creating
       * the new record.
       */
      const res =
        await axios.get<BatchListResponse>(
          `${url}/allbatch`,
          config
        );

      setBatchData(
        res.data.batchData
      );

      toast.success(
        `${newBatch.batchNumber} added successfully!`
      );

      /*
       * Preserve the existing behaviour:
       * briefly show the success notification
       * before closing the modal.
       */
      setTimeout(() => {
        handleClose();
      }, 600);
    } catch (error: unknown) {
      console.error(
        "Error Adding Batch:",
        error
      );

      /*
       * TypeScript:
       * A caught error is unknown.
       *
       * axios.isAxiosError() safely narrows it before
       * we access error.response.
       */
      if (axios.isAxiosError(error)) {
        const message =
          (
            error.response?.data as
              | {
                  message?: string;
                }
              | undefined
          )?.message;

        toast.error(
          message ||
            "Failed to add batch. Please try again."
        );

        return;
      }

      toast.error(
        "Failed to add batch. Please try again."
      );
    }
  };


  // ========================================
  // SHARED FORM STYLES
  // ========================================

  const labelStyle: CSSProperties = {
    fontWeight: 600,
    fontSize: "12px",
    color: "#475569",
    marginBottom: "6px",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  };

  const inputStyle: CSSProperties = {
    borderRadius: "8px",
    padding: "9px 12px",
    fontSize: "13px",
    border:
      "1px solid #e2e8f0",
    backgroundColor: "#fff",
    color: "#1e293b",
  };

  const disabledInputStyle:
    CSSProperties = {
    ...inputStyle,
    backgroundColor: "#f8fafc",
    color: "#94a3b8",
    cursor: "not-allowed",
    border:
      "1px solid #f1f5f9",
  };

  const errorStyle: CSSProperties = {
    fontSize: "11px",
    marginTop: "4px",
    color: "#ef4444",
  };


  return (
    <Modal
      show={show}
      onHide={handleClose}
      size="lg"
      centered
      style={modalStyle}
    >
      <ModalHeaderBlock
        title="Add Batch"
        icon={<GroupAdd />}
      />

      <Form
        onSubmit={
          formik.handleSubmit
        }
      >
        <Modal.Body
          style={{
            padding: "24px",
            backgroundColor:
              "#f9fafb",
          }}
        >
          {/* ========================================
              ROW 1: BATCH NUMBER + COURSE
          ======================================== */}

          <Row className="g-3 mb-3">
            <Col
              xs={12}
              md={6}
            >
              <Form.Label
                style={labelStyle}
              >
                <Tag
                  sx={{
                    fontSize: 14,
                  }}
                />
                Batch Number
              </Form.Label>

              <Form.Control
                type="text"
                name="batchNumber"
                value={
                  formik.values
                    .batchNumber
                }
                disabled
                style={
                  disabledInputStyle
                }
              />
            </Col>

            <Col
              xs={12}
              md={6}
            >
              <Form.Label
                style={labelStyle}
              >
                <School
                  sx={{
                    fontSize: 14,
                  }}
                />
                Course Name
              </Form.Label>

              <Form.Select
                name="courseName"
                value={
                  formik.values
                    .courseName
                }
                onChange={
                  handleCourseNameChange
                }
                onBlur={
                  formik.handleBlur
                }
                style={inputStyle}
              >
                <option value="">
                  Select Course
                </option>

                {courseData.map(
                  (course) => (
                    <option
                      key={
                        course._id
                      }
                      value={
                        course.courseName
                      }
                    >
                      {
                        course.courseName
                      }
                    </option>
                  )
                )}
              </Form.Select>

              {formik.errors
                .courseName &&
                formik.touched
                  .courseName && (
                  <div
                    style={
                      errorStyle
                    }
                  >
                    {
                      formik.errors
                        .courseName
                    }
                  </div>
                )}
            </Col>
          </Row>


          {/* ========================================
              ROW 2: DATES + SESSION TYPE
          ======================================== */}

          <Row className="g-3 mb-3">
            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <CalendarMonth
                  sx={{
                    fontSize: 14,
                  }}
                />
                Start Date
              </Form.Label>

              <Form.Control
                type="date"
                name="startDate"
                value={
                  formik.values
                    .startDate
                }
                onChange={
                  formik.handleChange
                }
                onBlur={
                  formik.handleBlur
                }
                style={inputStyle}
              />

              {formik.errors
                .startDate &&
                formik.touched
                  .startDate && (
                  <div
                    style={
                      errorStyle
                    }
                  >
                    {
                      formik.errors
                        .startDate
                    }
                  </div>
                )}
            </Col>


            {/* End date is calculated automatically */}
            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <CalendarMonth
                  sx={{
                    fontSize: 14,
                  }}
                />
                End Date (auto)
              </Form.Label>

              <Form.Control
                type="date"
                value={endDate}
                disabled
                style={
                  disabledInputStyle
                }
                placeholder="Select course & start date"
              />
            </Col>


            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <Wifi
                  sx={{
                    fontSize: 14,
                  }}
                />
                Session Type
              </Form.Label>

              <Form.Select
                name="sessionType"
                value={
                  formik.values
                    .sessionType
                }
                onChange={
                  formik.handleChange
                }
                onBlur={
                  formik.handleBlur
                }
                style={inputStyle}
              >
                <option value="">
                  Select Type
                </option>

                <option value="Online">
                  🌐 Online
                </option>

                <option value="At School">
                  🏫 At School
                </option>
              </Form.Select>

              {formik.errors
                .sessionType &&
                formik.touched
                  .sessionType && (
                  <div
                    style={
                      errorStyle
                    }
                  >
                    {
                      formik.errors
                        .sessionType
                    }
                  </div>
                )}
            </Col>
          </Row>


          {/* ========================================
              ROW 3: DAY + TIME + TARGET STUDENTS
          ======================================== */}

          <Row className="g-3 mb-3">
            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <Event
                  sx={{
                    fontSize: 14,
                  }}
                />
                Session Day
              </Form.Label>

              <Form.Select
                name="sessionDay"
                value={
                  formik.values
                    .sessionDay
                }
                onChange={
                  formik.handleChange
                }
                onBlur={
                  formik.handleBlur
                }
                style={inputStyle}
              >
                <option value="">
                  Select Day
                </option>

                <option value="Weekday">
                  📅 Weekday
                </option>

                <option value="Weekend">
                  🎉 Weekend
                </option>
              </Form.Select>

              {formik.errors
                .sessionDay &&
                formik.touched
                  .sessionDay && (
                  <div
                    style={
                      errorStyle
                    }
                  >
                    {
                      formik.errors
                        .sessionDay
                    }
                  </div>
                )}
            </Col>


            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <AccessTime
                  sx={{
                    fontSize: 14,
                  }}
                />
                Session Time
              </Form.Label>

              <Form.Select
                name="sessionTime"
                value={
                  formik.values
                    .sessionTime
                }
                onChange={
                  formik.handleChange
                }
                onBlur={
                  formik.handleBlur
                }
                style={inputStyle}
              >
                <option value="">
                  Select Time
                </option>

                <option value="Morning">
                  🌅 Morning
                </option>

                <option value="Afternoon">
                  ☀️ Afternoon
                </option>

                <option value="Evening">
                  🌆 Evening
                </option>
              </Form.Select>

              {formik.errors
                .sessionTime &&
                formik.touched
                  .sessionTime && (
                  <div
                    style={
                      errorStyle
                    }
                  >
                    {
                      formik.errors
                        .sessionTime
                    }
                  </div>
                )}
            </Col>


            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <People
                  sx={{
                    fontSize: 14,
                  }}
                />
                Target Students
              </Form.Label>

              <Form.Control
                type="number"
                name="targetStudent"
                value={
                  formik.values
                    .targetStudent
                }
                onChange={
                  formik.handleChange
                }
                onBlur={
                  formik.handleBlur
                }
                placeholder="e.g. 20"
                min={1}
                style={inputStyle}
              />

              {formik.errors
                .targetStudent &&
                formik.touched
                  .targetStudent && (
                  <div
                    style={
                      errorStyle
                    }
                  >
                    {
                      formik.errors
                        .targetStudent
                    }
                  </div>
                )}
            </Col>
          </Row>


          {/* ========================================
              ROW 4: COURSE FEE
          ======================================== */}

          <Row className="g-3">
            <Col
              xs={12}
              md={4}
            >
              <Form.Label
                style={labelStyle}
              >
                <AttachMoney
                  sx={{
                    fontSize: 14,
                  }}
                />
                Course Fee
              </Form.Label>

              <Form.Control
                type="text"
                name="courseFee"
                value={
                  formik.values
                    .courseFee
                }
                disabled
                style={
                  disabledInputStyle
                }
              />
            </Col>
          </Row>
        </Modal.Body>

        <ModalFooterBlock
          onClose={handleClose}
          submitText="Submit"
          submitting={
            formik.isSubmitting
          }
        />
      </Form>
    </Modal>
  );
}

export default ModalAddBatch;