// sidebar.styles.js
export const COLORS = {
  DARKER: "#030920",
  DARK: "#1734a8",
  TEXT: "rgba(255,255,255,0.78)",
  MUTED: "rgba(255,255,255,0.38)",
};

export const ANIM = {
  WIDTH_DURATION: 400,
  LABEL_DURATION: 160,
};

export const S = {
  sidebar: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "4px 0 28px rgba(0,0,0,0.5)",
    flexShrink: 0,
    zIndex: 100,
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
    padding: "10px 10px 0",
  },
  toggleBtn: {
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.15)",
    borderRadius: "8px",
    color: "#fff",
    cursor: "pointer",
    width: "30px",
    height: "30px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "17px",
    transition: "background 0.2s",
    flexShrink: 0,
    padding: 0,
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "8px 12px 14px",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    flexShrink: 0,
    minHeight: "52px",
    overflow: "hidden",
  },
  logoText: {
    color: "#f1f5f9",
    fontWeight: 700,
    fontSize: "15px",
    whiteSpace: "nowrap",
    letterSpacing: "0.4px",
    transformOrigin: "left center",
    overflow: "hidden",
  },
  nav: {
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    padding: "6px 0",
    scrollbarWidth: "none",
  },
  sectionLabel: {
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "1.6px",
    textTransform: "uppercase",
    padding: "14px 18px 5px",
    whiteSpace: "nowrap",
    overflow: "hidden",
  },

  // ✅ full-width divider so it aligns with logo border
  divider: {
    borderBottom: "1px solid rgba(255,255,255,0.10)",
    margin: "10px 0",
    width: "100%",
  },

  item: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    fontSize: "13.5px",
    fontWeight: 500,
    borderRadius: "9px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    position: "relative",
  },
  iconWrap: {
    flexShrink: 0,
    width: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  itemLabel: {
    flex: 1,
    transformOrigin: "left center",
    overflow: "hidden",
  },
  signout: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    color: "#f87171",
    fontSize: "13.5px",
    fontWeight: 500,
    borderTop: "1px solid rgba(255,255,255,0.08)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    flexShrink: 0,
  },
  tooltip: {
    position: "absolute",
    left: "54px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "#0a1020",
    color: "#f1f5f9",
    padding: "5px 11px",
    borderRadius: "7px",
    fontSize: "12px",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    zIndex: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    boxShadow: "0 4px 16px rgba(0,0,0,0.5)",
    transition: "opacity 0.15s ease",
  },
};