// ========================================
// BATCH SHARED TYPES
// ========================================
// This file contains the shared TypeScript types for Batch data.
//
// Keeping the Batch interface here means components such as
// ViewBatch, CustomisedBatchTables, ModalEditBatch, etc.
// can all use the same definition instead of creating
// separate interfaces in every component.


// TypeScript:
// These union types restrict the values to the options
// that our backend/frontend currently supports.

export type BatchStatus =
  | "Not Started"
  | "In Progress"
  | "Training Completed"
  | "Batch Completed";

export type BatchApprovalStatus =
  | "pending"
  | "approved"
  | "declined"
  | null;

export type SessionType =
  | "Online"
  | "At School";

export type SessionDay =
  | "Weekday"
  | "Weekend";

export type SessionTime =
  | "Morning"
  | "Afternoon"
  | "Evening";


// ========================================
// MAIN BATCH TYPE
// ========================================

export interface Batch {
  // MongoDB document ID.
  _id: string;

  // Automatically generated by the backend,
  // for example: "2026-0001".
  batchNumber: string;

  sessionType: SessionType;

  courseName: string;

  /*
   * Important:
   * The backend Mongoose schema currently stores
   * targetStudent as a String, even though the UI
   * displays it as a number.
   *
   * We therefore type the API value as string.
   * When we need to perform numeric comparisons later,
   * we will convert it using Number(batch.targetStudent).
   */
  targetStudent: string;

  sessionDay: SessionDay;

  sessionTime: SessionTime;

  // The backend schema defines fees as Number.
  fees: number;

  /*
   * Sequence number used by the backend when generating
   * the batchNumber.
   */
  seq?: number;

  /*
   * The backend provides a default value of 0.
   * It is optional here because older records may not
   * contain this field.
   */
  assignedStudentCount?: number;

  status: BatchStatus;

  /*
   * TypeScript:
   * These approval-related properties can be missing,
   * particularly on batches that have never gone through
   * the approval workflow.
   */
  requestedBy?: string;

  approvalStatus?: BatchApprovalStatus;

  approvedBy?: string | null;

  approvedAt?: string | null;

  /*
   * The controller currently uses this property during
   * the approval-email process, although it is not part
   * of the original Batch schema.
   *
   * Making it optional lets TypeScript represent the
   * existing API behaviour safely.
   */
  requestedByEmail?: string;

  /*
   * Similar to requestedByEmail, the approval controller
   * currently uses isApproved during approval/decline.
   */
  isApproved?: boolean;

  /*
   * Dates arrive from MongoDB/Express as ISO strings
   * in the frontend.
   */
  startDate: string;

  createdAt?: string;

  updatedAt?: string;

  /*
   * The current Batch frontend reads location and
   * createdBy for the table/filtering.
   *
   * They are NOT currently declared in the backend
   * Batch Mongoose schema, so we mark them optional
   * instead of pretending the API always returns them.
   *
   * We should review this frontend/backend mismatch
   * separately rather than changing application
   * behaviour during the TypeScript migration.
   */
  location?: string;

  createdBy?: string;
}