import { useState } from 'react';
import Modal from 'react-bootstrap/Modal';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import { useFormik } from 'formik';
import * as Yup from "yup";
import React from "react";
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { url } from '../../utils/constant';


function ModalAddBatch({show,setShow}){
    const navigate = useNavigate()

    const handleClose = () => {
        setShow(false)
        navigate('/batchdata')
        }
      
      const formSchema = Yup.object().shape({
        batchNumber: Yup.string().required(),
        courseName: Yup.string().required(),
        sessionDay: Yup.string().required(),
        targetStudent: Yup.string().required(),
        location:Yup.string().required(),
        sessionTime:Yup.string().required(),
        fees:Yup.number().required()
    })
    
    const formik = useFormik({
        initialValues: {
            batchNumber:"",
            sessionType:"",
            courseName:"",
            sessionDay:"",
            targetStudent:"",
            location:"",
            sessionTime:"",
            fees:""
        },
        validationSchema: formSchema,
        onSubmit: (values) => {
        console.log(values)
        addBatch(values)
        }
    })
    
    //keep the token in web-browser
    const token = sessionStorage.getItem('token')
    console.log(token)

    //Bearer authentication  is an HTTP authentication scheme that involves security tokens called bearer tokens. The name “Bearer authentication” can be understood as “give access to the bearer of this token.” The bearer token is a cryptic string, usually generated by the server in response to a login request. The client must send this token in the Authorization header when making requests to protected resources:
    let config={
        headers:{
            Authorization:`Bearer ${token}`
        }}

    const addBatch = async (newBatch)=>{
        console.log(newBatch)
        const res = await axios.post(`${url}/addbatch`,newBatch,config)
        console.log(res)
    }
    // When you click the save.>> update
    
   return(
    <>
        <Modal     
         show={show} onHide={handleClose}
          size="xl" >
        <Modal.Header closeButton>
          <Modal.Title  >Add Batch</Modal.Title>
        </Modal.Header>
        <Form onSubmit={formik.handleSubmit} className='px-5' style={{fontSize:"80%"}}>
        <Modal.Body>

        {/* Batch Number*/}
        <Form.Group className='my-3'>
          <Form.Label className='m-0'>Batch No.</Form.Label>
            <Form.Control type="batchNumber" 
            placeholder='Type your Batch No.' 
            name="batchNumber" 
            value={formik.values.batchNumber}
            onChange={formik.handleChange} /></Form.Group>
        
        {/* Session Type */}
        <Form.Group className='my-3'>
        <Form.Label className='m-0'>Session Type</Form.Label>
                    <Form.Control type="sessionType" placeholder='Type your Session Type' name="sessionType"
                    value={formik.values.sessionType}
                    onChange={formik.handleChange} />
        </Form.Group>

        {/* Course Name */}
        <Form.Group className='my-3'>
        <Form.Label className='m-0'>Course Name</Form.Label>
            <Form.Control type="courseName" placeholder='Type your Course Name' name="courseName"
            value={formik.values.courseName}
            onChange={formik.handleChange} />
        </Form.Group>

        {/* Session Day */}
        <Form.Group className='my-3'>
        <Form.Label className='m-0'>Session Day</Form.Label>
        <Form.Control type="sessionDay" placeholder='Type your Session Day' name="sessionDay"                        value={formik.values.sessionDay}
        onChange={formik.handleChange} />
        </Form.Group>

        {/* Target Student */}
        <Form.Group className='my-3'>
        <Form.Label className='m-0'>Target Student</Form.Label>
        <Form.Control type="targetStudent" placeholder='Type your Target Student' name="targetStudent"
        value={formik.values.targetStudent}
        onChange={formik.handleChange} />
        </Form.Group>

        {/* Session Time */}
        <Form.Group className='my-3'>
        <Form.Label className='m-0'>Session Time</Form.Label>
        <Form.Control type="sessionTime" placeholder='Type your Session Time' name="sessionTime"
        value={formik.values.sessionTime}
        onChange={formik.handleChange} />
        </Form.Group>

        {/* Fees */}
        <Form.Group className='my-3'>
        <Form.Label className='m-0'>Fees</Form.Label>
        <Form.Control type="fees" placeholder='Type your Fees' name="fees"
        value={formik.values.fees}
        onChange={formik.handleChange} />
        </Form.Group>
    
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
          <Button style={{backgroundColor:"#4e73df"}} type="submit">
            Save Changes
          </Button>
        </Modal.Footer>
        </Form>
      </Modal>
    </>
   )
}
export default ModalAddBatch